[project]
name = "quantumchess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "memory-profiler==0.61.0",
    "numpy>=2.3.5",
]
